// ES6 module syntax

const data = {
    fa:{
        RETURN: "برگشت",
        LOCK_CONVERSION: "بستن پست",
        UNLOCK_CONVERSION: "بازگشایی پست",
        EVENT_TITLE: "عنوان پست",
        EVENT_DESCRIPTION: "توضیحات پست",
        COMMUNITY_NAME: "نام انجمن",
        TITLE: "عنوان",
        Community: "انجمن",
        COMMUNITIES: "انجمن ها",
        CITY: "شهر",
        CANCEL: "انصراف",
        EDIT: "ویرایش",
        ARE_YOU_DELETE_EVENT: "آیا از حذف این پست اطمینان دارید؟",
        ARE_YOU_DELETE_COMMENT: "آیا از حذف این پیام اطمینان دارید؟",
        EVENT_EDIT: "ویرایش پست",
        DELETE: "حذف",
        MESSAGE_ARCHIVED: "این پیام آرشیو شده است.",
        COMMENT_DELETE: "حذف پیام",
        FULL_NAME: "نام و نام خانوادگی",
        SEND_MESSAGE: "ارسال پیام",
        SEND_MESSAGING: "در حال ارسال...",
        MESSAGES: "پیام ها",
        USERNAME: "نام کاربری",
        MESSAGE: "پیام",
        EMAIL: "ایمیل",
        ERROR: "خطا",
        LOGIN: "ورود",
        NONE: "هیچکدام",
        HOME: "خانه",
        COMMUNITY: "انجمن",
        COMMENT_NOT_FOUND: "هنوز پیامی برای این پست ثبت نشده است.",
        CONVERSION_NOT_FOUND: "هنوز هیچ پستی ثبت نشده است.",
        LOGOUT: "خروج",
        PASSWORD_VALID: "رمز عبور نباید کمتر از ۸ کاراکتر و شامل یک حرف بزرگ ، یک حرف کوچک و یک عدد باشد",
        CONFIRM: "تایید",
        LEAVE_COMMUNITY: "ترک انجمن",
        JOIN_COMMUNITY: "عضو انجمن",
        SORT: "مرتب سازی",
        EDIT_COMMUNITY: "ویرایش انجمن",
        BIG_COMMENT: "پرکامنت ترین ها",
        BIG_LIKE: "پرلایک ترین ها",
        LATEST: "جدیدترین ها",
        SEARCH: "جستجو",
        EVENT_PRIVATE: "این پست خصوصی و پیام ها از دید کاربران مخفی است.",
        NET_ERROR: "خطا در برقراری ارتباط با سرور",
        PLEASE_WAIT: "لطفا منتظر بمانید...",
        LOGGING: "در حال ورود...",
        ALREADY_ACCOUNT: "قبلاً حساب داشته اید؟",
        DO_NOT_ACCOUNT: "حساب کاربری ندارید؟",
        CREATE_ACCOUNT: "ایجاد حساب",
        RETURN_TO_HOME: "برگشت به خانه",
        MOBILE_NUMBER: "شماره موبایل",
        LOGIN_TO_ACCOUNT: "ورود به حساب کاربری",
        CREATE_AN_ACCOUNT: "ایجاد حساب کاربری",
        PASSWORD: "رمز عبور",
        RESET_PASSWORD: "بازگردانی رمز عبور",
        RESETTING_PASSWORD: "درحال بازگردانی...",
        SENDING: "درحال ارسال...",
        SEND_PASSWORD_RESET_LINK: "ارسال لینک بازیابی رمز عبور",
        HOW_FORGET_PASSWORD: "رمز عبور خود را فراموش کرده اید؟",
        FORGET_PASSWORD: "فراموشی رمز عبور",
        REGISTER_SUCCESSFULLY: "حساب کاربری با موفقیت ایجاد شد.",
        LOGIN_SUCCESSFULLY: "با موفقیت وارد شدید.",
        CONFIRM_PASSWORD: "تایید رمز عبور",
        EVENT_CREATED_SUCCESSFULLY: "پست با موفقیت ایجاد شد",
        COMMUNITY_CREATED_SUCCESSFULLY: "انجمن با موفقیت ایجاد شد",
        EVENT_EDITED_SUCCESSFULLY: "پست با موفقیت ویرایش شد",
        COMMUNITY_EDITED_SUCCESSFULLY: "انجمن با موفقیت ویرایش شد",
        EVENT_DELETED_SUCCESSFULLY: "پست با موفقیت حذف شد",
        MESSAGE_SEND_SUCCESSFULLY: "پیام با موفقیت ارسال شد",
        CREATE_EVENT: "ایجاد پست",
        COMMUNITY_DESCRIPTION: "توضیحات انجمن",
        CREATE_COMMUNITY: "ایجاد انجمن",
        CREATE_COMMENT: "ایجاد ییام",
        EVENT_LINK: "لینک پست",
        EVENT_DELETE: "حذف پست",
        PUBLISH_ON: "منتشر شده توسط: ",
        CREATE_CONVERSION: "ایجاد پست",
        CREATING_CONVERSION: "در حال ایجاد...",
        EDIT_CONVERSION: "ویرایش پست",
        EDITING_CONVERSION: "در حال ویرایش...",
        SHOW_COMMENTS: "پیام ها توسط عموم دیده شود",
        PRIVATE_COMMENT: "پیام خصوصی ارسال شود",
        PRIVATE: "خصوصی",
        COPY: "کپی",
        MESSAGE_DELETED: "این پیام توسط کاربر حذف شده است.",
        LINK_COPIED: "لینک با موفقیت کپی شد.",
    }
};
export {data}
