<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

class Comment extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function toArray($request)
    {
        $likes = $this->likes;
        $like = $likes->where('user_id',auth()->id())->first();
        return [
          'id' => $this->id,
          'event_id' => $this->event_id,
          'name' => $this->user->name,
          'content' => $this->content,
          'like' => $this->when($like,function ()use($like){return $like->action == 'like';}),
          'like_count' => $likes->where('action','like')->count(),
          'dislike_count' => $likes->where('action','dislike')->count(),
          'date' => $this->date,
          'deleted_at' => $this->deleted_at,
        ];
    }
    public function with($request)
    {
        return ['error' => false]; // TODO: Change the autogenerated stub
    }
}
