<?php

namespace App\Http\Resources;

use Carbon\Carbon;
use Illuminate\Http\Resources\Json\JsonResource;
use Morilog\Jalali\CalendarUtils;
use Morilog\Jalali\Jalalian;

class Event extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function toArray($request)
    {
        return [
          'id' => $this->id,
          'user_id' => $this->user_id,
          'username' => $this->user->name ?? '',
          'community_id' => $this->community_id,
          'title' => $this->title,
          'description' => $this->description,
          'status' => $this->status,
          'date' => $this->created_at->diffForHumans(),
        ];
    }

    public function with($request)
    {
        return ['error' => false]; // TODO: Change the autogenerated stub
    }
}
